### ISSUE TITLE
What is the best way to decide whether a gene is NITE or LITE regulated? 

### ISSUE THREAD

**Issue by shaistamadad** [cistrome/MIRA#11]
Hi, 
Is there a set of p-values associated with the NITE scores for genes and cells in your RP model?  I am trying to find a quantitative metric to decide whether a set of genes I am interested in are NITE or LITE regulated. I understand from your tutorial that plotting the chromatin differential plots is one way of checking this. 

```
lite_model.get_logp(expr_adata=rna_sub, atac_adata=atac_data)
nite_model.get_logp(expr_adata=rna_sub, atac_adata=atac_data)
mira.tl.get_NITE_score_genes(rna_sub)
mira.tl.get_NITE_score_cells(rna_sub)
```

**Comment by AllenWLynch** [comment]
We do not usually define a hard cut off between LITE and NITE, but the way to decide which way a gene swings is to visualize the distribution of NITE scores across all modeled genes. If a gene you are interested in is on the tail of the distribution, I would consider it more NITE.
