### ISSUE TITLE
Is MIRA being actively developed / maintained

### ISSUE THREAD

**Issue by akundaje** [cistrome/MIRA#25]
Hi.

Was just curious whether MIRA is being actively developed and maintained. As part of a consortium, we are actively canvasing interesting single cell analysis toolkits and wanted to prioritize those that the developers plan to actively maintain and develop.

Thanks
Anshul.

**Comment by AllenWLynch** [comment]
Hi Anshul,

MIRA is actively maintained, and is in fact receiving a large update soon which will add batch effect correction to our variational topic models. The manuscript describing our algorithm is accepted in principle at Nature Communications.

Let me know if you have any questions,
AL

On Jun 6, 2023, at 5:23 PM, Anshul Kundaje ***@***.***> wrote:

﻿

Hi.

Was just curious whether MIRA is being actively developed and maintained. As part of a consortium, we are actively canvasing interesting single cell analysis toolkits and wanted to prioritize those that the developers plan to actively maintain and develop.

Thanks
Anshul.

**Comment by akundaje** [comment]
Awesome. Thanks!
