### ISSUE TITLE
mira.tl.get_distance_to_TSS(): human genome equivalent for parameter : genome_file 

### ISSUE THREAD

**Issue by shaistamadad** [cistrome/MIRA#5]
Hi, 
It is not clear to me what the mm10.genome.sorted file data represents in the following code from your tutorial. It appears to be the chromosome sizes? I want to run this analysis for a human multiome dataset- where can I find the equivalent information for human genome please? 

```
mira.tl.get_distance_to_TSS(atac_main,
                            tss_data=tss_data,
                            peak_chrom='chr',
                            peak_start='start',
                            peak_end='end',
                            gene_id='geneSymbol',
                            gene_chrom='chrom',
                            gene_strand='strand',
                            gene_start='txStart',
                            gene_end='txEnd',
                            **genome_file='mm10.genome.sorted')
```

Would the following work for human genome? 

chr1	         248956422
chr2 	242193529
chr3 	198295559
chr4 	190214555
chr5 	181538259
chr6 	170805979
chr7 	159345973
chr8	145138636
chr9	138394717
chr10 	133797422
chr11 	135086622	
chr12 	133275309
chr13 	114364328
chr14 	107043718
chr15 	101991189
chr16 	90338345
chr17 	83257441
chr18 	80373285
chr19 	80373285
chr20 	64444167
chr21 	46709983
chr22 	50818468
X	56040895
Y	57227415

Thanks so much for your help.

**Comment by AllenWLynch** [comment]
Hi,

Here is where you can get chromsizes:
https://hgdownload.cse.ucsc.edu/goldenpath/hg38/bigZips/latest/hg38.chrom.sizes

In general, this is a good resource for genome metadata:
https://hgdownload.cse.ucsc.edu/goldenpath/hg38/bigZips/

AL

________________________________
From: shaistamadad ***@***.***>
Sent: Monday, February 7, 2022 6:23 PM
To: cistrome/MIRA ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cistrome/MIRA] mira.tl.get_distance_to_TSS(): human genome equivalent for parameter : genome_file (Issue #5)


Hi,
It is not clear to me what the mm10.genome.sorted file data represents in the following code from your tutorial. It appears to be the chromosome sizes? I want to run this analysis for a human multiome dataset- where can I find the equivalent information for human genome please?

mira.tl.get_distance_to_TSS(atac_main,
                            tss_data=tss_data,
                            peak_chrom='chr',
                            peak_start='start',
                            peak_end='end',
                            gene_id='geneSymbol',
                            gene_chrom='chrom',
                            gene_strand='strand',
                            gene_start='txStart',
                            gene_end='txEnd',
                            **genome_file='mm10.genome.sorted')


thanks so much for your help.

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcistrome%2FMIRA%2Fissues%2F5&data=04%7C01%7C%7C94d9e1a5e54a4a0008cb08d9ea99314f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637798765953827173%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XoHlM4Dsshpt9Iv46gUi2RaEhiFYfF83M5MLos2QzEM%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAE43JPAWHGYVMC2XP5SJNJ3U2BO67ANCNFSM5NY6KTUA&data=04%7C01%7C%7C94d9e1a5e54a4a0008cb08d9ea99314f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637798765953827173%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9xsmgyYHLahJFtVOzMx1GiKJtBZd7%2FFCZLLTGMBRefk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C94d9e1a5e54a4a0008cb08d9ea99314f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637798765953827173%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Povb7zh9vkEb1sUkDaiGm02vwNmBCsC%2BFSZydOmjhok%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C94d9e1a5e54a4a0008cb08d9ea99314f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637798765953827173%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=InL5qXEIOJza8DiGhuLtiLvddz4W8urIZ%2BzCqy0dksY%3D&reserved=0>.

**Comment by shaistamadad** [comment]
thanks very much!
