### ISSUE TITLE
IndexError: index 39840 is out of bounds for axis 0 with size 20479

### ISSUE THREAD

**Issue by shaistamadad** [cistrome/MIRA#8]
Hi, 

I get an IndexError when I try to use the trained LITE model to predict gene expression for RNA data using the accessibility data. 
```
lite_model.fit(expr_adata=rna_sub, atac_adata=atac_sub)
```

IndexError: index 39840 is out of bounds for axis 0 with size 20479

Thanks so much for your help.

**Comment by shaistamadad** [comment]
resolved now. thank you!

**Comment by AllenWLynch** [comment]
Hi,

Can you provide the whole stack trace please? My intuition is that this has something to do with the TSS annotations having duplicates. Did you reannotate TSS distances using de-duplicated canonical TSS?

Thanks,
AL
________________________________
From: shaistamadad ***@***.***>
Sent: Thursday, February 17, 2022 6:44 PM
To: cistrome/MIRA ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cistrome/MIRA] IndexError: index 39840 is out of bounds for axis 0 with size 20479 (Issue #8)


Hi,

I get an IndexError when I try to use the trained LITE model to predict gene expression for RNA data using the accessibility data.

lite_model.fit(expr_adata=rna_sub, atac_adata=atac_sub)


IndexError: index 39840 is out of bounds for axis 0 with size 20479

Thanks so much for your help.

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcistrome%2FMIRA%2Fissues%2F8&data=04%7C01%7C%7C2d3fa10794a24c13b2ac08d9f277ce97%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637807418661906658%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=G1hMV8e1eW2h%2Fb82UqNSjZYF0GlM5dwgpVDcH%2FWR05A%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAE43JPFSLUCLQEER2GY5ZH3U3WI6NANCNFSM5OWKA7CA&data=04%7C01%7C%7C2d3fa10794a24c13b2ac08d9f277ce97%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637807418661906658%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=k5KO%2F2mWGgiRGDuKoH6%2BSrUrC%2BIAt%2Bmr%2B3MkEBcZGpI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C2d3fa10794a24c13b2ac08d9f277ce97%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637807418661906658%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PQ%2BibKdTPkfoCLpn5ZkLM5s8f7Ej1zRQD3rbou6hG88%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C2d3fa10794a24c13b2ac08d9f277ce97%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637807418661906658%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pUpx%2Boar%2BJW693ZdTfEgQkUlxEInl5GELNGU24NnPug%3D&reserved=0>.
